<h5>US Census Population 2020 to 2025 Extraction</h5>
<h6></h6>

In [1]:
import pandas as pd
import numpy as np
import re #import regular expressions module (set of string that matches the criteria)
from collections import defaultdict
import us #import us library
pop_census = pd.read_csv("USCensus_2020_2024.csv")

In [5]:
#inspecting data using Python
#display data first 5 rows
pop_census.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,...,NRANK_NPCHG2020,NRANK_NPCHG2021,NRANK_NPCHG2022,NRANK_NPCHG2023,NRANK_NPCHG2024,NRANK_PPCHG2020,NRANK_PPCHG2021,NRANK_PPCHG2022,NRANK_PPCHG2023,NRANK_PPCHG2024
0,10,0,0,0,United States,331515736,331577720,332099760,334017321,336806231,...,X,X,X,X,X,X,X,X,X,X
1,20,1,0,0,Northeast Region,57617706,57431458,57252533,57159597,57398303,...,4,4,4,4,3,4,4,4,3,3
2,30,1,1,0,New England,15122011,15057350,15118145,15175633,15263573,...,8,4,5,9,9,9,4,5,5,4
3,30,1,2,0,Middle Atlantic,42495695,42374108,42134388,41983964,42134730,...,9,8,9,6,5,8,8,9,7,6
4,20,2,0,0,Midwest Region,68998970,68984258,68872831,68903297,69186401,...,3,3,3,3,4,3,3,3,4,4

In [13]:
#checking for missing values
#pop_census.isnull().sum()
#no null

In [10]:
#view all columns
print(pop_census.columns.tolist())

['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'NAME', 'ESTIMATESBASE2020', 'POPESTIMATE2020', 'POPESTIMATE2021', 'POPESTIMATE2022', 'POPESTIMATE2023', 'POPESTIMATE2024', 'NPOPCHG_2020', 'NPOPCHG_2021', 'NPOPCHG_2022', 'NPOPCHG_2023', 'NPOPCHG_2024', 'PPOPCHG_2020', 'PPOPCHG_2021', 'PPOPCHG_2022', 'PPOPCHG_2023', 'PPOPCHG_2024', 'NRANK_ESTBASE2020', 'NRANK_POPEST2020', 'NRANK_POPEST2021', 'NRANK_POPEST2022', 'NRANK_POPEST2023', 'NRANK_POPEST2024', 'NRANK_NPCHG2020', 'NRANK_NPCHG2021', 'NRANK_NPCHG2022', 'NRANK_NPCHG2023', 'NRANK_NPCHG2024', 'NRANK_PPCHG2020', 'NRANK_PPCHG2021', 'NRANK_PPCHG2022', 'NRANK_PPCHG2023', 'NRANK_PPCHG2024']

In [12]:
#drop columns
pop_census_1 = pop_census.drop(columns=pop_census.loc[:, 'SUMLEV':'STATE'].columns)
pop_census_1 = pop_census_1.drop(columns=pop_census_1.loc[:, 'NPOPCHG_2020':'NRANK_PPCHG2024'].columns)
pop_census_1.head()

,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024
0,United States,331515736,331577720,332099760,334017321,336806231,340110988
1,Northeast Region,57617706,57431458,57252533,57159597,57398303,57832935
2,New England,15122011,15057350,15118145,15175633,15263573,15386085
3,Middle Atlantic,42495695,42374108,42134388,41983964,42134730,42446850
4,Midwest Region,68998970,68984258,68872831,68903297,69186401,69596584

In [14]:
pop_census_1.to_csv('clean_us_census.csv', index=False)